/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package sync

import (
	"context"
	"errors"
	"fmt"

	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"sigs.k8s.io/controller-runtime/pkg/client"
	sigyaml "sigs.k8s.io/yaml"

	"accord/internal/configmapmaterial"
	"accord/internal/inventory"
)

// +kubebuilder:rbac:groups=argoproj.io,resources=applications,verbs=get;create;patch
// +kubebuilder:rbac:groups=argoproj.io,resources=applicationsets,verbs=get;create;patch

const fieldOwner = "accord-sync-operator"

// argoExpectedAPIVersion is the only apiVersion sync-operator will apply.
// Anything else is treated as a path/manifest mismatch (review §1.4).
const argoExpectedAPIVersion = "argoproj.io/v1alpha1"

// PathManifestMismatchError is a typed error returned by ApplyInventoryYAML when
// the file-path identity does not match the parsed manifest. Callers (e.g. the
// webhook handler) MUST treat this as a non-recoverable per-file failure and
// MUST NOT retry: a mismatch indicates either a malformed commit or an active
// attempt to inject an unrelated resource through an inventory path.
type PathManifestMismatchError struct {
	Field        string // "apiVersion", "kind", "namespace", "name"
	PathExpect   string // value derived from the file path
	ManifestSeen string // value observed inside the manifest
}

func (e *PathManifestMismatchError) Error() string {
	return fmt.Sprintf("path/manifest mismatch on %s: path expects %q but manifest has %q",
		e.Field, e.PathExpect, e.ManifestSeen)
}

// IsPathManifestMismatch reports whether err originated from path/manifest
// identity validation in ApplyInventoryYAML.
func IsPathManifestMismatch(err error) bool {
	var m *PathManifestMismatchError
	return errors.As(err, &m)
}

// ApplyInventoryYAML applies Git YAML to the cluster using server-side apply
// after enforcing path↔manifest identity (review §1.4) and injecting
// accord.io/sync-content-hash (material hash from inventory normalization)
// per docs/phase1-sync.md.
//
// `parsed` is the file path parsed by ParseInventoryExportPath. The function
// returns *PathManifestMismatchError when the manifest's apiVersion/kind/
// namespace/name disagrees with the path; the webhook handler reports this as
// "error" and skips the file without retry.
func ApplyInventoryYAML(ctx context.Context, c client.Client, parsed ParsedInventoryPath, gitYAML []byte) error {
	incomingHash, err := inventory.MaterialHashFromNormalizedYAML(gitYAML)
	if err != nil {
		return fmt.Errorf("compute material hash from Git YAML: %w", err)
	}

	doc := inventory.FirstYAMLDocument(gitYAML)
	jsonBytes, err := sigyaml.YAMLToJSON(doc)
	if err != nil {
		return fmt.Errorf("convert yaml to json: %w", err)
	}
	obj := &unstructured.Unstructured{}
	if err := obj.UnmarshalJSON(jsonBytes); err != nil {
		return fmt.Errorf("parse unstructured: %w", err)
	}

	if err := validatePathManifestIdentity(parsed, obj); err != nil {
		return err
	}

	ann := obj.GetAnnotations()
	next := make(map[string]string)
	for k, v := range ann {
		next[k] = v
	}
	next[configmapmaterial.SyncContentHashAnnotationKey] = incomingHash
	obj.SetAnnotations(next)

	if err := c.Patch(ctx, obj, client.Apply, client.FieldOwner(fieldOwner), client.ForceOwnership); err != nil {
		return fmt.Errorf("server-side apply: %w", err)
	}
	return nil
}

// validatePathManifestIdentity enforces that the manifest's identity (apiVersion,
// kind, namespace, name) exactly matches what the inventory file path declares.
// The path is the trusted side: it is generated by inventory-controller and
// gated through ParseInventoryExportPath in the webhook entry point, so any
// discrepancy is interpreted as the manifest being suspicious.
func validatePathManifestIdentity(parsed ParsedInventoryPath, obj *unstructured.Unstructured) error {
	if got := obj.GetAPIVersion(); got != argoExpectedAPIVersion {
		return &PathManifestMismatchError{
			Field:        "apiVersion",
			PathExpect:   argoExpectedAPIVersion,
			ManifestSeen: got,
		}
	}
	expectedKind, err := ArgoKindFromPlural(parsed.PluralKind)
	if err != nil {
		// Should not happen if the caller already passed parsed through
		// ParseInventoryExportPath, but keep defense-in-depth.
		return fmt.Errorf("resolve kind for plural %q: %w", parsed.PluralKind, err)
	}
	if got := obj.GetKind(); got != expectedKind {
		return &PathManifestMismatchError{
			Field:        "kind",
			PathExpect:   expectedKind,
			ManifestSeen: got,
		}
	}
	if got := obj.GetNamespace(); got != parsed.Namespace {
		return &PathManifestMismatchError{
			Field:        "namespace",
			PathExpect:   parsed.Namespace,
			ManifestSeen: got,
		}
	}
	if got := obj.GetName(); got != parsed.Name {
		return &PathManifestMismatchError{
			Field:        "name",
			PathExpect:   parsed.Name,
			ManifestSeen: got,
		}
	}
	return nil
}
